# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GuiTable.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(598, 461)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/cct/Encriptar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tblProcess = QtWidgets.QTableWidget(self.centralwidget)
        self.tblProcess.setEnabled(True)
        self.tblProcess.setGeometry(QtCore.QRect(40, 50, 501, 161))
        self.tblProcess.setObjectName("tblProcess")
        self.tblProcess.setColumnCount(2)
        self.tblProcess.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tblProcess.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblProcess.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblProcess.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblProcess.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblProcess.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Bitstream Charter")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tblProcess.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblProcess.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Bitstream Charter")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tblProcess.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblProcess.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Bitstream Charter")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tblProcess.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblProcess.setItem(2, 1, item)
        self.tblProcess.horizontalHeader().setVisible(False)
        self.tblProcess.horizontalHeader().setCascadingSectionResizes(False)
        self.tblProcess.horizontalHeader().setDefaultSectionSize(250)
        self.tblProcess.horizontalHeader().setHighlightSections(False)
        self.tblProcess.horizontalHeader().setMinimumSectionSize(50)
        self.tblProcess.horizontalHeader().setSortIndicatorShown(False)
        self.tblProcess.horizontalHeader().setStretchLastSection(False)
        self.tblProcess.verticalHeader().setVisible(False)
        self.tblProcess.verticalHeader().setCascadingSectionResizes(False)
        self.tblProcess.verticalHeader().setDefaultSectionSize(50)
        self.tblProcess.verticalHeader().setHighlightSections(False)
        self.tblProcess.verticalHeader().setMinimumSectionSize(50)
        self.tblProcess.verticalHeader().setSortIndicatorShown(False)
        self.tblProcess.verticalHeader().setStretchLastSection(True)
        self.lblProcess = QtWidgets.QLabel(self.centralwidget)
        self.lblProcess.setGeometry(QtCore.QRect(40, 10, 501, 41))
        self.lblProcess.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblProcess.setStyleSheet("background-color: rgb(167, 167, 167);")
        self.lblProcess.setAlignment(QtCore.Qt.AlignCenter)
        self.lblProcess.setWordWrap(False)
        self.lblProcess.setObjectName("lblProcess")
        self.tblFileProcess = QtWidgets.QTableWidget(self.centralwidget)
        self.tblFileProcess.setEnabled(True)
        self.tblFileProcess.setGeometry(QtCore.QRect(40, 250, 501, 181))
        self.tblFileProcess.setRowCount(6)
        self.tblFileProcess.setObjectName("tblFileProcess")
        self.tblFileProcess.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tblFileProcess.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblFileProcess.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblFileProcess.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblFileProcess.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Bitstream Charter")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tblFileProcess.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Bitstream Charter")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tblFileProcess.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Bitstream Charter")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tblFileProcess.setItem(0, 2, item)
        self.tblFileProcess.horizontalHeader().setVisible(False)
        self.tblFileProcess.horizontalHeader().setCascadingSectionResizes(False)
        self.tblFileProcess.horizontalHeader().setDefaultSectionSize(163)
        self.tblFileProcess.horizontalHeader().setHighlightSections(False)
        self.tblFileProcess.horizontalHeader().setMinimumSectionSize(50)
        self.tblFileProcess.horizontalHeader().setSortIndicatorShown(False)
        self.tblFileProcess.horizontalHeader().setStretchLastSection(False)
        self.tblFileProcess.verticalHeader().setVisible(False)
        self.tblFileProcess.verticalHeader().setCascadingSectionResizes(False)
        self.tblFileProcess.verticalHeader().setDefaultSectionSize(50)
        self.tblFileProcess.verticalHeader().setHighlightSections(False)
        self.tblFileProcess.verticalHeader().setMinimumSectionSize(50)
        self.tblFileProcess.verticalHeader().setSortIndicatorShown(False)
        self.tblFileProcess.verticalHeader().setStretchLastSection(True)
        self.lblFileProcess = QtWidgets.QLabel(self.centralwidget)
        self.lblFileProcess.setGeometry(QtCore.QRect(40, 210, 501, 41))
        self.lblFileProcess.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblFileProcess.setStyleSheet("background-color: rgb(167, 167, 167);")
        self.lblFileProcess.setAlignment(QtCore.Qt.AlignCenter)
        self.lblFileProcess.setWordWrap(False)
        self.lblFileProcess.setObjectName("lblFileProcess")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Resumen"))
        item = self.tblProcess.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tblProcess.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tblProcess.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tblProcess.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tblProcess.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        __sortingEnabled = self.tblProcess.isSortingEnabled()
        self.tblProcess.setSortingEnabled(False)
        item = self.tblProcess.item(0, 0)
        item.setText(_translate("MainWindow", "Archivos Procesados"))
        item = self.tblProcess.item(0, 1)
        item.setText(_translate("MainWindow", "0 Archivos"))
        item = self.tblProcess.item(1, 0)
        item.setText(_translate("MainWindow", "Tiempo"))
        item = self.tblProcess.item(1, 1)
        item.setText(_translate("MainWindow", "0 minuto 0 Segundos"))
        item = self.tblProcess.item(2, 0)
        item.setText(_translate("MainWindow", "Tamaño Total"))
        item = self.tblProcess.item(2, 1)
        item.setText(_translate("MainWindow", "0 KB"))
        self.tblProcess.setSortingEnabled(__sortingEnabled)
        self.lblProcess.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Proceso Ejeccutado:</span> Encriptación</p></body></html>"))
        item = self.tblFileProcess.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tblFileProcess.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tblFileProcess.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tblFileProcess.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        __sortingEnabled = self.tblFileProcess.isSortingEnabled()
        self.tblFileProcess.setSortingEnabled(False)
        item = self.tblFileProcess.item(0, 0)
        item.setText(_translate("MainWindow", "Nombre"))
        item = self.tblFileProcess.item(0, 1)
        item.setText(_translate("MainWindow", "Tiempo de Procesamiento"))
        item = self.tblFileProcess.item(0, 2)
        item.setText(_translate("MainWindow", "Tamaño"))
        self.tblFileProcess.setSortingEnabled(__sortingEnabled)
        self.lblFileProcess.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Archivos</span> Encriptados</p></body></html>"))
#import Resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
